<a href="https://colab.research.google.com/github/Jubrixx/Deber/blob/main/ActividadIA_con_Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as numpy

aux = numpy.array([1,2,4,5])
print(aux)
print(aux.shape)


aux=numpy.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))


print('---------------------------')
tmp=numpy.zeros([4,4])
print(tmp)


print('---------------------------')
tmp=numpy.full([4,4],5)
print(tmp)


print('---------------------------')
tmp=numpy.eye(4,4)
print(tmp)


print('---------------------------')
tmp=numpy.ones([4,4])
print(tmp)

[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
---------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
---------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
---------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

tmp=10*np.random.random([3,3])
print(tmp)

[[0.82116111 6.78207588 4.01557982]
 [4.63595929 3.45477089 4.08748764]
 [0.56561939 2.89018958 7.29465389]]


In [ ]:
print(tmp[:2,:2])

[[0.82116111 6.78207588]
 [4.63595929 3.45477089]]


In [ ]:
print(tmp[:2,1:3])

[[6.78207588 4.01557982]
 [3.45477089 4.08748764]]


In [ ]:
print(tmp[:1,:1])

[[0.82116111]]


In [ ]:
print(tmp[2,2])

7.294653892517374


In [ ]:
tmp=10*np.random.random([3,3])
print(tmp)

[[5.21342103 8.56907865 3.63011997]
 [3.52672406 9.88918676 9.10697429]
 [9.05966214 5.99881003 0.93889041]]


In [ ]:
mask=tmp>5
print(tmp[mask])

[5.21342103 8.56907865 9.88918676 9.10697429 9.05966214 5.99881003]


In [ ]:
nrosEnteros = np.random.randint(0, 10, size=(4, 4))
print(nrosEnteros)


print('---------------------------')
nrosEnteros = nrosEnteros[nrosEnteros % 2 == 0]
print(nrosEnteros)


[[8 4 6 8]
 [4 8 1 6]
 [0 7 1 5]
 [1 3 7 7]]
---------------------------
[8 4 6 8 4 8 6 0]
