<a href="https://colab.research.google.com/github/Jubrixx/Deber/blob/main/ActividadIA_con_Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 4))
print(A)
print(A.shape)

print(' ')
print('---------------------------')
print(' ')

B = np.random.randint(1, 11, size=(3, 4))
print(B)
print(B.shape)

print(' ')
print('---------------------------')
print(' ')

print('Suma de Matrices')
print(A+B)

print(' ')
print('---------------------------')
print(' ')

print('Resta de Matrices')
print(A-B)

print(' ')
print('---------------------------')
print(' ')

print('Multiplicacion de Matrices')
print(A*B)

print(' ')
print('---------------------------')
print(' ')

print('Matriz')
print(np.add(A,B))

print(' ')
print('---------------------------')
print(' ')

print('Multiplicacion de Matriz')
print(np.multiply(A,B))

print(' ')
print('---------------------------')
print(' ')

print('Division de Matriz')
print(np.divide(A,B))

[[ 1  6  1  9]
 [10  9  7  5]
 [10  9 10  3]]
(3, 4)
 
---------------------------
 
[[ 8  7  8  7]
 [ 1 10  9 10]
 [ 9  1 10  7]]
(3, 4)
 
---------------------------
 
Suma de Matrices
[[ 9 13  9 16]
 [11 19 16 15]
 [19 10 20 10]]
 
---------------------------
 
Resta de Matrices
[[-7 -1 -7  2]
 [ 9 -1 -2 -5]
 [ 1  8  0 -4]]
 
---------------------------
 
Multiplicacion de Matrices
[[  8  42   8  63]
 [ 10  90  63  50]
 [ 90   9 100  21]]
 
---------------------------
 
Matriz
[[ 9 13  9 16]
 [11 19 16 15]
 [19 10 20 10]]
 
---------------------------
 
Multiplicacion de Matriz
[[  8  42   8  63]
 [ 10  90  63  50]
 [ 90   9 100  21]]
 
---------------------------
 
Division de Matriz
[[ 0.125       0.85714286  0.125       1.28571429]
 [10.          0.9         0.77777778  0.5       ]
 [ 1.11111111  9.          1.          0.42857143]]


In [ ]:
print('Matriz A')
A = np.random.randint(1, 11, size=(2, 3))
print(A)

print(' ')
print('---------------------------')
print(' ')

print('Matriz B')
B = np.random.randint(1, 11, size=(3, 4))
print(B)

print(' ')
print('---------------------------')
print(' ')

print('Multiplicacion de Matrices Respetando la Regla')
print(np.dot(A,B))
print('---------------------------')
print(A.dot(B))

Matriz A
[[9 4 3]
 [1 9 9]]
 
---------------------------
 
Matriz B
[[10  6  4  6]
 [ 2  3  4  9]
 [ 9 10  8 10]]
 
---------------------------
 
Multiplicacion de Matrices Respetando la Regla
[[125  96  76 120]
 [109 123 112 177]]
---------------------------
[[125  96  76 120]
 [109 123 112 177]]


In [ ]:
print('Matriz A')
A = np.random.randint(1, 11, size=(2, 2))
print(A)

print(' ')
print('---------------------------')
print(' ')

print('Matriz Transpuesta de A')
print(A.T)


Matriz A
[[7 9]
 [1 4]]
 
---------------------------
 
Matriz Transpuesta
[[7 1]
 [9 4]]
 
---------------------------
 


In [ ]:
print('Matriz A')
A = np.random.randint(1, 11, size=(4, 3))
print(A)

print(' ')
print('---------------------------')
print(' ')

print('Matriz B')
B= np.array([1,0,2])
print(B)

print(' ')
print('---------------------------')
print(' ')

print('Matriz C')
C= np.empty_like(A)
print(C)

print(' ')
print('---------------------------')
print(' ')

print('Suma de Matriz A + B')
r = (A+B)
print(r)

print(' ')
print('---------------------------')
print(' ')

print('Suma de Matriz C + R(A+B)')
print(r+C)


Matriz A
[[10  2  6]
 [ 4  6  9]
 [ 2  2  4]
 [ 6  6  7]]
 
---------------------------
 
Matriz B
[1 0 2]
 
---------------------------
 
Matriz C
[[4 9 3]
 [5 5 2]
 [9 3 7]
 [9 5 8]]
 
---------------------------
 
Suma de Matriz A + B
[[11  2  8]
 [ 5  6 11]
 [ 3  2  6]
 [ 7  6  9]]
 
---------------------------
 
Suma de Matriz C + R(A+B)
[[15 11 11]
 [10 11 13]
 [12  5 13]
 [16 11 17]]


In [ ]:
print('Matriz A')
A = np.array([1,2,3])

print(A)

print(' ')
print('---------------------------')
print(' ')

print('Matriz B')
B = np.array([1,2,3])
matriz = np.tile(B, (6, 1))
print(matriz)

print(' ')
print('---------------------------')
print(' ')

print('Matriz C')
C = np.random.randint(0, 11, size=(6, 6))
print(C)
promedio = np.mean(C)
print(' ')
print('Promedio')
print(promedio)

print(' ')
print('---------------------------')
print(' ')

promedio1 = np.mean(C, axis=1)
print(' ')
print('Promedio por filas')
print(promedio1)

print(' ')
print('---------------------------')
print(' ')

promedio2 = np.mean(C, axis=0)
print(' ')
print('Promedio por columnas')
print(promedio2)

Matriz A
[1 2 3]
 
---------------------------
 
Matriz B
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
 
---------------------------
 
Matriz C
[[ 6  3  1  7  7  4]
 [ 3  1  3  3  2  7]
 [ 3  7  5 10  5  4]
 [ 9  4  1  6  0  8]
 [ 4  0  8 10  4 10]
 [ 0  5  6  3  2  3]]
 
Promedio
4.555555555555555
 
---------------------------
 
 
Promedio por filas
[4.66666667 3.16666667 5.66666667 4.66666667 6.         3.16666667]
 
---------------------------
 
 
Promedio por columnas
[4.16666667 3.33333333 4.         6.5        3.33333333 6.        ]
