<a href="https://colab.research.google.com/github/Jubrixx/Deber/blob/main/TareaNumpyExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# Import numpy as np and see the version

# your code here
import numpy as np

pass

In [ ]:
# Create a 1D array of numbers from 0 to 9
# your code here
lista=list(range(9))
print(lista)
pass


[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)
pass

[0.80635854 0.26960209 0.98989888 0.83491957 0.0279989  0.4710947
 0.77388857 0.33261296 0.         0.38239101]


In [ ]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])
pass

8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
pass

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])
pass

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
tmp=10*np.random.random((4,4))
mask=tmp>0
print(tmp)
print('-----------------------------------------------')
print(mask)
pass

[[8.63991255 3.55797926 2.00341537 7.87773143]
 [0.17552732 4.70003894 0.36240761 0.98370457]
 [9.60913682 4.14277972 4.90185562 7.96106744]
 [3.81524221 2.14289665 6.5422909  5.89288143]]
-----------------------------------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# Extract all odd numbers from arr
# your code here
tmp = np.random.randint(1, 11, size=(4, 4))
print(tmp)
print('---------------')
mask = np.mod(tmp, 2) == 0
print(tmp[mask])
pass

[[ 9  5  1  1]
 [ 8  4  4  2]
 [ 6  7  5  9]
 [ 2 10  8  5]]
---------------
[ 8  4  4  2  6  2 10  8]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
tmp = np.arange(10,50)
print(tmp)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
vectorInvertido = tmp[::-1]
print(vectorInvertido)
pass

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
tmp = np.random.randint(1, 101, size=(10, 10))
minimo = np.min(tmp)
maximo = np.max(tmp)
print("Matriz")
print(tmp)
print("Minimo")
print(minimo)
print("Maximo")
print(maximo)
pass

Matriz
[[ 50  89  55  70  64  53  53  95  78   6]
 [  2  22   1  59  91  27  93  53  18  32]
 [ 45  94  77  57  61  24  49  67  73  95]
 [ 86  39  90  36  59  44  36 100  76  30]
 [ 53  30  23  87  81  12  91  37  97  11]
 [  1  43  68  53  57  59  33  78  43  31]
 [ 45   7  62  86   1  87  51  57  36  70]
 [ 65  28  88   6  74  56  41   6  30  96]
 [  3  90  19 100  43  17   8  10  92  55]
 [ 43  36  68  84  10  59  18   3  78  14]]
Minimo
1
Maximo
100


In [ ]:
# Create a 3x3x3 array with random values
tmp2 = np.random.random((3,3,3))
print(tmp2)
pass

[[[0.93657998 0.56439572 0.50183434]
  [0.00325855 0.0100005  0.17558289]
  [0.212742   0.82234794 0.15263721]]

 [[0.39816912 0.51352046 0.46731767]
  [0.81392597 0.71606835 0.10292673]
  [0.41203671 0.93740695 0.30411296]]

 [[0.13151881 0.95586273 0.60634409]
  [0.50410542 0.10148732 0.82694752]
  [0.04435629 0.99634681 0.42346415]]]


In [ ]:
# Replace all odd numbers in arr with -1
# your code here
tmp = np.random.randint(1, 11, size=(3, 3, 3))
print(tmp)
print('--------------')
tmp[tmp % 2 == 1] = -1
print(tmp)
pass

[[[ 9  5  5]
  [ 7  2  3]
  [ 3  8  3]]

 [[ 2  1  8]
  [ 4  3  1]
  [10  7  9]]

 [[ 7  5  6]
  [ 9  5  3]
  [ 4  8  1]]]
--------------
[[[-1 -1 -1]
  [-1  2 -1]
  [-1  8 -1]]

 [[ 2 -1  8]
  [ 4 -1 -1]
  [10 -1 -1]]

 [[-1 -1  6]
  [-1 -1 -1]
  [ 4  8 -1]]]


In [ ]:
# Create an array of type float
tmpF = np.random.rand(5)
print(tmpF)
pass

[0.41322583 0.87265948 0.06739593 0.38827954 0.18417704]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
lista = list(range(12))
lista = np.array(lista)
dos_d_array = lista.reshape(2, 6)
print(dos_d_array)
pass

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valoresComunes = np.intersect1d(Z1, Z2)
print(Z1)
print('---------------------')
print(Z2)
print('---------------------')
print(valoresComunes)

pass

[1 4 4 6 0 9 0 7 1 9]
---------------------
[0 6 5 8 2 6 3 3 8 8]
---------------------
[0 6]


In [ ]:
#  Consider two random array A and B, check if they are equal


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print('Array A')
print(A)
print('Array B')
print(B)

if np.array_equal(A,B):
  print('Son iguales')
else:
  print('Son diferentes')

pass

Array A
[0 0 1 1 0]
Array B
[1 0 1 0 1]
Son diferentes


In [ ]:
# Stack arrays a and b vertically
# your code here
print('Array A')
print(A)
print('Array B')
print(B)
matrizAplicadaVertical = np.vstack((A,B))
print("Stacked Array:")
print(matrizAplicadaVertical)
pass

Array A
[0 0 1 1 0]
Array B
[1 0 1 0 1]
Stacked Array:
[[0 0 1 1 0]
 [1 0 1 0 1]]


In [ ]:
# Stack the arrays a and b horizontally.
# your code here
print('Array A')
print(A)
print('Array B')
print(B)
matrizAplicadaHorizontal = np.hstack((A, B))
print("Stacked Array:")
print(matrizAplicadaHorizontal)
pass

Array A
[0 0 1 1 0]
Array B
[1 0 1 0 1]
Stacked Array:
[0 0 1 1 0 1 0 1 0 1]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
print(tmp)
print('----------------------------------------------')
valores = tmp[(tmp>=5)&(tmp<=10)]
print(valores)
# pass

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
----------------------------------------------
[ 5  6  7  8  9 10]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
"""Arrays"""
# a = np.array([5, 7, 9, 8, 6, 4, 5])
a = np.random.randint(1, 10, 7)
print("Array A")
print(a)
# b = np.array([6, 3, 4, 8, 9, 7, 1])
b = np.random.randint(1, 10, 7)
print("Array B")
print(B)
print('---------------')

"""Metodo 1"""
print("Metodo 1")
def parMax(a, b):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(a, b)

c= parMax(a, b)
print(c)
print('---------------')

print("Metodo 2")
"""Metodo 2"""
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

c = np.array([maxx(x, y) for x, y in zip(a, b)])
print(c)


Array A
[3 3 4 5 6 7 2]
Array B
[1 0 1 0 1]
---------------
Metodo 1
[3 3 4 5 6 7 7]
---------------
Metodo 2
[3 3 4 5 6 7 7]


In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

# your code here
arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]
print('---------')
print("Cambio de columnas 1 y 2")
print(arr)
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------
Cambio de columnas 1 y 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)

[[5.73039225 7.08038186 5.14444546]
 [5.72643451 5.48005089 9.49240523]
 [7.60236611 7.4483306  8.87130347]
 [8.54669065 8.19303979 8.85151783]
 [8.11965015 6.25347203 9.48456015]]
